[package]
name = "sutom-rules"
version = "1.0.0"
edition = "2021"
description = "lib qui continent les regles de parsing du sutom"
license = "MIT OR Apache-2.0"
authors = ["paq1"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
